import { useState } from "react";

const TYPES = ["Sports & sparring", "Study & DSA", "Hackathon / build", "Chai & hangout"];

export default function PostRequestModal({ open, onClose }) {
  const [type, setType] = useState(TYPES[0]);
  const [description, setDescription] = useState("");
  const [spot, setSpot] = useState("Badminton Court 2");
  const [timing, setTiming] = useState("Tonight @ 8 PM");
  const [posted, setPosted] = useState(false);
  if (!open) return null;
  function submit(event) { event.preventDefault(); if (!description.trim()) return; const posts = JSON.parse(localStorage.getItem("converge-posts") || "[]"); localStorage.setItem("converge-posts", JSON.stringify([{ type, description, spot, timing, createdAt: new Date().toISOString() }, ...posts])); setPosted(true); setDescription(""); }
  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-ink/75 p-4 backdrop-blur-sm"><form onSubmit={submit} className="w-full max-w-lg rounded-2xl border border-edge bg-surface p-5 shadow-2xl sm:p-7"><div className="flex items-start justify-between"><div><span className="mono-label text-[10px] text-violet-bright">Campus live board</span><h2 className="mt-1 font-display text-2xl font-semibold">Post a match request</h2></div><button type="button" onClick={onClose} className="text-xl text-text-faint hover:text-text" aria-label="Close">×</button></div>{posted ? <div className="mt-8 rounded-xl border border-live/30 bg-live/10 p-5"><p className="font-display text-lg font-semibold text-live">Posted to the campus board.</p><p className="mt-2 text-sm text-text-muted">People looking for the same energy can now find you.</p><button type="button" onClick={onClose} className="mt-5 rounded-xl bg-violet px-5 py-2 text-sm font-medium text-white">Done</button></div> : <><p className="mt-6 text-xs text-text-faint">What are you looking for?</p><div className="mt-2 grid grid-cols-2 gap-2">{TYPES.map((item) => <button type="button" key={item} onClick={() => setType(item)} className={`rounded-xl border p-3 text-left text-xs ${type === item ? "border-violet bg-violet/15 text-violet-bright" : "border-edge text-text-muted hover:border-violet/50"}`}>{item}</button>)}</div><label className="mt-5 block text-xs text-text-muted">Describe your request<textarea required value={description} onChange={(event) => setDescription(event.target.value)} rows={3} className="mt-2 w-full resize-none rounded-xl border border-edge bg-ink/40 p-3 text-sm text-text placeholder:text-text-faint focus:border-violet" placeholder="Need 1 badminton doubles partner for Court 2 tonight..." /></label><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs text-text-muted">Campus spot<select value={spot} onChange={(event) => setSpot(event.target.value)} className="mt-2 w-full rounded-xl border border-edge bg-ink/40 px-3 py-2.5 text-sm text-text"><option>Badminton Court 2</option><option>Cafeteria Chai Corner</option><option>3rd Floor Maker Space</option><option>Library Commons</option></select></label><label className="text-xs text-text-muted">Timing<input value={timing} onChange={(event) => setTiming(event.target.value)} className="mt-2 w-full rounded-xl border border-edge bg-ink/40 px-3 py-2.5 text-sm text-text" /></label></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl border border-edge px-4 py-2 text-sm text-text-muted">Cancel</button><button type="submit" className="rounded-xl bg-violet px-5 py-2 text-sm font-medium text-white hover:bg-violet-bright">Publish request</button></div></>}</form></div>;
}
